### ISSUE TITLE
New Data

### ISSUE THREAD

**Issue by Benambridge** [footballcsv/europe-champions-league#1]
Hi there - thanks so much for this resource - it was the only one I could find with complete Champions' League and European Cup data. I don't suppose there's any way you'd be able to add the last couple of seasons' data in the same format? Thanks!!

**Comment by geraldb** [comment]
You can get the latest seasons (incl. goal getters)  from the open football.db - see <https://github.com/openfootball/europe-champions-league>. Sorry there's only so much I can do. Still working on the csv import into football.db right now. Please, send questions and comments to the forum / mailing list <https://groups.google.com/group/opensport>. Maybe someone else can help out. Cheers. Prost.

**Comment by Benambridge** [comment]
OK thanks very much!

Ben
